spring.application.name=skylimit
spring.datasource.url=jdbc:mysql://localhost:3306/products
spring.datasource.username=root
spring.datasource.password=S@tish200
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=${SERVER_PORT:8081}